website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: EPPS 6302 Assignments
        menu:
          - href: about.qmd
            text: Assignment 1
          - href: Assignment 2.qmd
            text: Assignment 2
          - href: Assignment 3.qmd
            text: Assignment 3
          - href: Assignment 6.qmd
            text: Assignment 6

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
