website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Assignment 1
      - href: Assignment 2.qmd
        text: Assignment 2
      - href: Assignment 3.qmd
        text: Assignment 3
      - href: Assignment 6.qmd
        text: Assignment 6
      - href: Assignment 7.qmd
        text: Assignment 7
      - href: Assignment 8.qmd
        text: Assignment 8

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

