project:
  type: website

website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Assignment 2.qmd
      - Assignment 3.qmd
      - Assignment 6.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

