project:
  type: website
website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CSV.qmd
      - epps6313.qmd
      - text: EPPS6302 Assignments
        menu: 
          - Assignment1.qmd
          - Assignment2.qmd
          - Assignment3.qmd
          - Assignment6.qmd
          - Assignment7.qmd
          - Assignment8.qmd
          - epps6302.qmd
      - text: EPPS6323 Assignments
        menu:   
          - 6323HW2.qmd
          - 6323HW3.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
