project:
  type: website
website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CSV.qmd
      - text: Assignments
        menu: 
          - Assignment1.qmd
          - Assignment2.qmd
          - Assignment3.qmd
          - Assignment6.qmd
          - Assignment7.qmd
          - Assignment8.qmd
       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
