website:
  title: "Jhanvi Kannan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu: 
          - about.qmd
          - Assignment 2.qmd
          - Assignment 3.qmd
          - Assignment 6.qmd
          - Assignment 7.qmd
          - Assignment 8.qmd
       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual
